### PR TITLE
Feature: Removed auto generated files and added to gitignore

### PR DESCRIPTION
**Pull request by wdconinc**
This removes equations.txt etc which can all be regenerated.

### CODE REVIEW

**Comment by wdconinc** [comment]
@rahmans1 @cameronc137  Who is monitoring this?

**Comment by cameronc137** [comment]
I'm loosely monitoring this

**Comment by wdconinc** [comment]
Who's in charge of merging?

**Comment by cameronc137** [comment]
I guess Sakib and I both are

**Pull request merged**
