### PR TITLE
Updates from today

### PR DESCRIPTION
**Pull request by cameronc137**
Here are some updates I've made today - see if they are reasonable (and yes, this is a backwards scenario from what merges normally are)

### CODE REVIEW

**Comment by cameronc137** [comment]
I just did a check, to see if this old "nomenclature" branch is in any way different from the up-to-date "feature-detector-nomenclature" branch. It is not. The only difference is a junk commit that only contains changes to some of the outputs that shouldn't have been tracked in git in the first place. https://github.com/JeffersonLab/remoll-detector-generator/commit/a19fbbdbb83707e9fe5945a9c7231c632d35734c

**Comment by wdconinc** [comment]
Translation? Merge or no merge needed?

**Comment by cameronc137** [comment]
I think that no merge is required and this branch can be deleted (as well as the other branches that have been recently merged)

**Comment by rahmans1** [comment]
I would delete the nomenclature branch. It seems like a stale branch.

**Comment by rahmans1** [comment]
Axel and I am looking through the other branches and deleting ones that seems unnecessary at this point. I think the feature-clean-junk and the feature-detector-nomenclature branches can also be deleted. But I will double check.

**Pull request closed without merging**
